## Comandos para la extension Rest Client

## CRUD Colecciones

### Obtener todos las categorias
GET http://localhost:3005/api/coleccion

### Obtener uno
GET http://localhost:3005/api/coleccion/66b5954bf8925423aa283015

### Crear un nuevo recurso
POST http://localhost:3005/api/coleccion
Content-Type: application/json

{
    "name": "Game of thrones"
}

### Modificar un recurso
PUT http://localhost:3005/api/coleccion/66b5954bf8925423aa283015
Content-Type: application/json

{
    "name": "house of the dragon",
}

### Eliminar un recurso
DELETE http://localhost:3005/api/coleccion/6695b405754f295c28475aay

