## Comandos para la extension Rest Client

## CRUD Suscripciones

### Obtener todos los precios
GET http://localhost:3005/api/suscripcionprecio

### Obtener todos los precios de una suscripcion
GET http://localhost:3005/api/suscripcionprecio/66e2200e9e6b7fc6686057b0

### Crear un nuevo recurso
POST http://localhost:3005/api/suscripcionprecio/66e25d6be1df0bfe4b0d14f9
Content-Type: application/json

{
    "startDate": "2024-09-12T15:30:00Z",
    "amount": 2000,
    "suscripcionId": "66e25d6be1df0bfe4b0d14f9"
}

### Eliminar un recurso
DELETE http://localhost:3005/api/suscripcionprecio/se_ignora/66e2200e9e6b7fc6686057b1
