## Comandos para la extension Rest Client

## CRUD Suscripciones

### Obtener todos los precios
GET http://localhost:3005/api/suscripcionprecio

### Obtener todos los precios de una suscripcion
GET http://localhost:3005/api/suscripcionprecio/66f2b6d08d6516a2432b5195

### Crear un nuevo recurso
POST http://localhost:3005/api/suscripcionprecio/66f2b4402a02dc4980521cc6
Content-Type: application/json

{
    "startDate": "2024-09-12T15:30:00Z",
    "amount": 2000,
    "suscripcionId": "66f2b4402a02dc4980521cc6"
}

### Eliminar un recurso
DELETE http://localhost:3005/api/suscripcionprecio/se_ignora/66ef0a1081b62c092e2f9672
