## Comandos para la extension Rest Client

## CRUD Suscripciones

### Obtener todos los precios
GET http://localhost:3005/api/suscripcionprecio

### Obtener todos los precios de una suscripcion
GET http://localhost:3005/api/suscripcionprecio/670474817afe2582774c758e

### Obtener uno los precios de una suscripcion
GET http://localhost:3005/api/suscripcionprecio/670475aa7afe2582774c7593/670475aa7afe2582774c7595

### Crear un nuevo recurso
POST http://localhost:3005/api/suscripcionprecio/670474817afe2582774c758e
Content-Type: application/json

{
    "startDate": "2024-09-13T16:30:00Z",
    "amount": 2000,
    "suscripcionId": "670474817afe2582774c758e"
}

### Eliminar un recurso
DELETE http://localhost:3005/api/suscripcionprecio/670474817afe2582774c758e/67057eb643bf03f93c3ce0a7
