## Comandos para la extension Rest Client

## CRUD Suscripciones

### Obtener todos las suscripciones
GET http://localhost:3005/api/suscripcion

### Obtener uno
GET http://localhost:3005/api/suscripcion/66e25d6be1df0bfe4b0d14f9

### Crear un nuevo recurso
POST http://localhost:3005/api/suscripcion
Content-Type: application/json

{
    "type": "New"
}

### Modificar un recurso
PUT http://localhost:3005/api/suscripcion/66e0907b0da73b3a64602837
Content-Type: application/json

{
    "type": "D"
}

### Eliminar un recurso
DELETE http://localhost:3005/api/suscripcion/66e084096f592eb21fbe4d80
