## Comandos para la extension Rest Client

## CRUD Usuarios

### Obtener todos los Usuarios
GET http://localhost:3000/api/usuario

### Obtener uno
GET http://localhost:3000/api/usuario/667221387abd545ec8a6ffa7

### Crear un nuevo recurso
POST http://localhost:3000/api/usuario
Content-Type: application/json

{
    "usuario": "Angel",
    "contra": "pass",
    "email":"aaa@cc.bb",
    "tipo":"Admin"
}

### Modificar un recurso
PUT http://localhost:3000/api/usuario/667221387abd545ec8a6ffa7
Content-Type: application/json

{
    "usuario": "Not418",
    "contra": "I'm not in a teapot",
    "email":"mbarletta@hcdn.gob.ar",
    "tipo":"Diputado"
}

### Eliminar un recurso
DELETE http://localhost:3000/api/usuario/101
