## Comandos para la extension Rest Client

## CRUD Usuarios

### Obtener todos los Usuarios
GET http://localhost:3005/api/usuario

### Obtener uno
GET http://localhost:3005/api/usuario/66b5954bf8925423aa283012

### Crear un nuevo recurso
POST http://localhost:3005/api/usuario
Content-Type: application/json

{
    "usuario": "Pedro",
    "contra": "pass",
    "email":"dasda@cc.bb",
    "tipo":"Cliente"
}

### Modificar un recurso
PUT http://localhost:3005/api/usuario/66b5954bf8925423aa283012
Content-Type: application/json

{
    "usuario": "Pedro Pascal",
    "contra": "I'm not in a teapot",
    "email":"dasda@cc.bb",
    "tipo":"Cliente"
}

### Eliminar un recurso
DELETE http://localhost:3005/api/usuario/6695b405754f295c28475aae
